[View in Colaboratory](https://colab.research.google.com/github/himu30/Machine_learning_with_python/blob/master/assignment_17.ipynb)

# Assignment_17 ->  PCA (principal of component analysis)

In [0]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Q-1.)**

***Importing MNIST dataset from sklearn***

In [4]:
#importing mnist dataset from sklearn
from sklearn.datasets import load_digits 
digit = load_digits()
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

***Saving data features and targets into variables***

In [16]:
# data is stored in x whereas target is in y variable
x = digit.data
print(x)
y = digit.target
print(y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


**Q-2.) Feature scaling**

In [39]:
#feature scaling using StandardScaler
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(x) 
x_std


array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

**Q-3.)** ***Spliting dataset into training and testing***

In [0]:
#spliting data into training and testing set
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x_std , y ,test_size = 0.4, random_state = 20) 


**Q-4.)** ***Performing PCA***

In [0]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.96 )

#fiting the training part in 
x_train = pca.fit_transform(x_train)

x_test = pca.transform(x_test)


**Q-5.)** ***Classification through Logistic Regression***

In [62]:
#Classification usng logistic regression model
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()

#fiting the training part into model
log.fit(x_train , y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [0]:
#prediction over model
prediction = log.predict(x_test)

**Q-6.) **

**a.) Accuracy Score**

In [64]:
#accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_test , prediction)

0.9401947148817803

**b.) Confusion matrix**

In [65]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test , prediction)

array([[62,  0,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 72,  1,  1,  0,  0,  0,  0,  0,  1],
       [ 0,  0, 63,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 71,  0,  3,  0,  1,  4,  1],
       [ 0,  0,  0,  0, 73,  0,  0,  1,  1,  0],
       [ 1,  0,  0,  0,  0, 69,  0,  0,  0,  1],
       [ 0,  2,  0,  0,  2,  0, 67,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0, 78,  0,  1],
       [ 0,  3,  0,  0,  0,  2,  2,  0, 56,  1],
       [ 1,  1,  0,  0,  0,  3,  0,  1,  6, 65]])

**c.) Classification Report**

In [66]:
# Classification report
from sklearn.metrics import classification_report
classification_report(y_test , prediction,labels = None, digits = 3)

'             precision    recall  f1-score   support\n\n          0      0.969     0.984     0.976        63\n          1      0.923     0.960     0.941        75\n          2      0.969     1.000     0.984        63\n          3      0.973     0.887     0.928        80\n          4      0.973     0.973     0.973        75\n          5      0.896     0.972     0.932        71\n          6      0.971     0.944     0.957        71\n          7      0.963     0.975     0.969        80\n          8      0.836     0.875     0.855        64\n          9      0.929     0.844     0.884        77\n\navg / total      0.941     0.940     0.940       719\n'