[View in Colaboratory](https://colab.research.google.com/github/himu30/Machine_learning_with_python/blob/master/assignment_14.ipynb)

# **Assignment** -**14**     ***NAIVE BAYES***

**Q-1.)**  P(yes/sunny) = p(sunny/yes) * p(yes) / p(sunny)
                
                Answer - 3/5

In [52]:
!pip install --upgrade lxml

Requirement already up-to-date: lxml in /usr/local/lib/python3.6/dist-packages (4.2.1)


**Q-2.)** 

In [0]:
#importing libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [54]:
from sklearn import datasets

#importing dataset
iris = datasets.load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
#training and testing , split
from sklearn.model_selection import train_test_split
#x = iris.data
#y = iris.target

x_train , x_test , y_train, y_test =train_test_split(iris.data , iris.target , test_size = 0.5 , random_state =20)

In [56]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train ,y_train)
print(gnb)

GaussianNB(priors=None)


In [0]:
# for predictions
g_pred = gnb.predict(x_test)

In [58]:
#classification report using GaussianNB
from sklearn.metrics import classification_report
classification_report(y_test , g_pred)

'             precision    recall  f1-score   support\n\n          0       1.00      1.00      1.00        24\n          1       0.89      1.00      0.94        33\n          2       1.00      0.78      0.88        18\n\navg / total       0.95      0.95      0.94        75\n'

In [59]:
#confusion matrix using GaussianNB
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, g_pred)

array([[24,  0,  0],
       [ 0, 33,  0],
       [ 0,  4, 14]])

In [60]:
#MultinomialNB
from sklearn.naive_bayes import MultinomialNB
mnb = MultinomialNB()
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:
#multinomial prediction
m_pred = mnb.predict(x_test)

In [62]:
#classification report using multinomialNB
from sklearn.metrics import classification_report
classification_report(y_test, m_pred)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'             precision    recall  f1-score   support\n\n          0       1.00      1.00      1.00        24\n          1       0.00      0.00      0.00        33\n          2       0.35      1.00      0.52        18\n\navg / total       0.40      0.56      0.45        75\n'

In [63]:
#confusion matrix using multinomialNB
from sklearn.metrics import confusion_matrix
confusion_matrix( y_test, m_pred)

array([[24,  0,  0],
       [ 0,  0, 33],
       [ 0,  0, 18]])